### ISSUE TITLE
Can't access via leftnav menu

### ISSUE THREAD

**Issue by nathan-io** [stepanenko3/nova-command-runner#1]
laravel/framework                  v9.5.1
laravel/nova                       4.0.0   
stepanenko3/nova-command-runner    v4.0.6

After installing and configuring, the "Command Runner" menu heading appears in the left nav, but it doesn't toggle any menu options: https://gyazo.com/974f17eba212f8aa65562b2f70be839b.png

I _can_ see the command runner dashboard with our configured commands if I hit route directly: http://site.test/nova/command-runner/

**Comment by stepanenko3** [comment]
@nathan-io,

Thanks for your issue
I fixed it in [Version 4.0.7](https://github.com/stepanenko3/nova-command-runner/releases/tag/v4.0.7)
