### ISSUE TITLE
History limit does not limit the result list

### ISSUE THREAD

**Issue by CrusherRL** [stepanenko3/nova-command-runner#13]
I found out that the history is not limited correctly. All Result will be displayed.

Example from Doc:
// Limit the command run history to latest 10 runs
'history'  => 10

Or do i understand that config wrongly? :)

**Comment by stepanenko3** [comment]
@CrusherRL 

Fixed in new release https://github.com/stepanenko3/nova-command-runner/releases/tag/v4.2.6
