### ISSUE TITLE
Buttons of the Vue components are not displayed correctly

### ISSUE THREAD

**Issue by HolgerHatGarKeineNode** [stepanenko3/nova-command-runner#14]
I have already tried to understand why the buttons lack style information. But I just couldn't find the reason.

![image](https://github.com/stepanenko3/nova-command-runner/assets/123783602/38079cd4-fc94-4ea0-b845-5f52318a56ab)

![image](https://github.com/stepanenko3/nova-command-runner/assets/123783602/e5530899-bff5-495c-a692-5d9958636a23)

Laravel: _v9.52.16_
Laravel Nova: _v4.29.4 (Silver Surfer)_
nova-command-runner: _Version 4.2.5_

This was also carried out, but without success.

> php artisan view:clear
> rm -rf node_modules && npm i && npm dev

Could there be a reason why the buttons are not displayed correctly?
Something seems to be wrong with Vue.

**Comment by webcodecs** [comment]
I am tackling the same problem.

**Comment by stepanenko3** [comment]
I don't have time to fix it right now. If you make PR, I'm ready to accept.

Or I'll fix it later

**Comment by abordage** [comment]
@stepanenko3, happy new year! Hope you are fine.

If you have time, please take a look https://github.com/stepanenko3/nova-command-runner/pull/15

**Comment by stepanenko3** [comment]
@abordage @scottasmith @mic2100  @webcodecs @HolgerHatGarKeineNode 

Fixed in new release https://github.com/stepanenko3/nova-command-runner/releases/tag/v4.2.6
