### ISSUE TITLE
The CSS/Style conflicts with Laravel Nova.

### ISSUE THREAD

**Issue by asis77** [stepanenko3/nova-command-runner#26]
Hi @stepanenko3 ,

We are currently using your package and have encountered an issue regarding CSS/Style conflicts with Laravel Nova. When integrating your package with our Laravel project, we noticed that there are conflicts between the styles of your package and those of Laravel Nova. This is causing visual inconsistencies and layout problems in our application.

Could you please investigate this issue and provide guidance on how we can resolve these conflicts? Let us know if you need any additional information from our end.

Thank you!

<img width="975" alt="Screenshot 2024-03-27 at 9 22 19 PM" src="https://github.com/stepanenko3/nova-command-runner/assets/5397772/6503cdca-cdcb-438e-9c23-1ff755102cda">

**Comment by stepanenko3** [comment]
What version of the package are you using?

**Comment by asis77** [comment]
> What version of the package are you using?

Package : "stepanenko3/nova-command-runner": "^4.0",
Laravel : "laravel/framework": "^10.0",

**Comment by stepanenko3** [comment]
@Asis77 it was fixed in the latest version, try to put ^4.3.4

**Comment by asis77** [comment]
> @asis77 it was fixed in the latest version, try to put ^4.3.4

Thanks!
