### ISSUE TITLE
Class bit found

### ISSUE THREAD

**Issue by borcherds-ralph** [stepanenko3/nova-command-runner#3]
I have installed and configured this following the instructions and I get the following error when trying to log into Nova

Error Class "Stepanenko3\NovaCommandRunner\CommandRunner" not found

From the composer install process
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking stepanenko3/nova-command-runner (v4.1.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading stepanenko3/nova-command-runner (v4.1.0)
  - Installing stepanenko3/nova-command-runner (v4.1.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

php artisan vendor:publish --provider="Stepanenko3\NovaCommandRunner\ToolServiceProvider"
Copied Directory [/vendor/stepanenko3/nova-command-runner/config] To [/config]
Publishing complete.

From NovaSerfviceProvider.php
 public function tools()
    {
        return [
            new \Stepanenko3\NovaCommandRunner\CommandRunner,
        ];
    }

**Comment by stepanenko3** [comment]
@borcherds-ralph 

Hi,

please, update Stepanenko3\NovaCommandRunner\CommandRunner to Stepanenko3\NovaCommandRunner\CommandRunnerTool
