### ISSUE TITLE
ReferenceError: __ is not defined when hitting "Run" button

### ISSUE THREAD

**Issue by dm-pf** [stepanenko3/nova-command-runner#30]
laravel: 10.48.4
nova: 4.33.1
nova-command-runner: 4.3.5

<img width="690" alt="image" src="https://github.com/stepanenko3/nova-command-runner/assets/100700999/e440ceff-c4f4-4949-ada9-3f06e89c9ca6">

**Comment by abordage** [comment]
Same problem

**Comment by dm-pf** [comment]
This issue was introduced in 4.3.5. Downgrading to 4.3.4 works as expected.

**Comment by kiritokatklian** [comment]
Tagging @stepanenko3 in case they missed this. I'm having the same issue on:
- Laravel 11.7
- Nova 4.33.2
- Nova command runner: 4.3.5

And this isn't the only issue. Downgrading to <=4.3.4 works (make sure to clear cache, including cached JS in the browser), but results in another issue #36

I downgraded back to 4.2.7 which didn't have either issues.

**Comment by kiritokatklian** [comment]
@stepanenko3 bump in case you missed it 😄
